substitutions:
  name: small-garage-door
  friendly_name: Small Garage Door

packages:
  Athom_Technology.Garage_Door_Opener: github://athom-tech/esp32-configs/athom-garage-door.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: WgnaV6OH5u8WDicDi2LJ3wQl7GvAo9rsQAy+4012NsM=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
