substitutions:
  device_name: kids-bathroom-exhaust
  friendly_name: Kids Bathroom Exhaust
  icon: mdi:fan
  room: Kids Bathroom

packages:
  device_basis: !include templates/treatlife_single_pole_fan.yaml
