substitutions:
  device_name: kitchen-light
  device_id: kitchen_light
  friendly_name: Kitchen Light
  icon: mdi:lightbulb
  room: "Kitchen"

packages:
  device_basis:   !include  templates/treatlife_three_way.yaml