substitutions:
  device_name: living-room-fan-switch
  friendly_name: Living Room Fan Switch
  icon: mdi:fan
  room: Living Room

packages:
  device_basis: !include templates/treatlife_three_way.yaml
