substitutions:
  device_name: living-room-front-light
  device_id: living_room_front_light
  friendly_name: Living Room Front Light
  room: Living Room

packages:
  device_basis: !include templates/treatlife_three_way_dimmer.yaml