substitutions:
  device_name: maksim-bathroom-exhaust
  friendly_name: Maksim Bathroom Exhaust
  icon: mdi:fan
  room: Maksim Bathroom

packages:
  device_basis: !include templates/treatlife_single_pole_fan.yaml
