substitutions:
  device_name: maksim-bathroom-light
  friendly_name: Maksim Bathroom Light
  icon: mdi:lightbulb
  room: Maksim Bathroom

packages:
  device_basis: !include templates/treatlife_dimmer.yaml
