substitutions:
  device_name: upstairs-hallway-light
  friendly_name: Upstairs Hallway Light
  icon: mdi:lightbulb
  room: Upstairs Hallway

packages:
  device_basis: !include templates/treatlife_three_way.yaml
