substitutions:
  device_name: kids-bathroom-bathtub-light
  device_id: kids_bathroom_bathtub_light
  friendly_name: Kids Bathroom Bathtub Light
  icon: mdi:lightbulb  
<<: !include templates/treatlife_single_pole.yaml