substitutions:
  device_name: living-room-christmas-tree
  device_id: living_room_christmas_tree
  friendly_name: Living Rooom Christmas Tree
  # Higher value gives lower watt readout
  current_res: "0.00221"
  # Lower value gives lower voltage readout
  voltage_div: "940"

<<: !include templates/efun_plug.yaml