substitutions:
  device_name: sprinklers
  friendly_name: Sprinklers
  d0_name: 
  d1_name: Flower Beds
  d2_name: Front Lawn Road
  d3_name: Front Lawn
  d4_name: Side Yard Right
  d5_name: Back Yard Right
  d6_name: Back Yard Left
  d7_name: 

<<: !include templates/network_ha_config.yaml

esphome:
  name: ${device_name}
  platform: ESP8266
  board: nodemcuv2

switch:
  - platform: gpio
    name: ${d1_name}
    pin: D1
    id: S1
    inverted: yes
    interlock: &interlock_group [S1, S2, S3, S4, S5, S6]
  - platform: gpio
    name: ${d2_name}
    pin: D2
    id: S2
    inverted: yes
    interlock: *interlock_group
  - platform: gpio
    name: ${d3_name}
    pin: D3
    id: S3
    inverted: yes
    interlock: *interlock_group
  - platform: gpio
    name: ${d4_name}
    pin: D4
    id: S4
    inverted: yes
    interlock: *interlock_group
  - platform: gpio
    name: ${d5_name}
    pin: D5
    id: S5
    inverted: yes
    interlock: *interlock_group
  - platform: gpio
    name: ${d6_name}
    pin: D6
    id: S6
    inverted: yes
    interlock: *interlock_group
  # - platform: gpio
  #   name: ${d7_name}
  #   pin: D7
  #   id: S7
  #   inverted: yes
  #   interlock: *interlock_group
  # - platform: gpio
  #   name: ${d0_name}
  #   pin: D0
  #   id: S0
  #   inverted: yes
  #   interlock: *interlock_group
