packages:
  device_basis: !include network_ha_config.yaml

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: ${room}
  min_version: 2024.6.0
  platformio_options:
    board_build.mcu: esp32c3
    board_build.variant: esp32c3
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  flash_size: 4MB
  variant: ESP32C3
  framework:
    type: esp-idf
    version: recommended

logger:
  baud_rate: 115200
  level: ${log_level}
  hardware_uart: UART0

esp32_improv:
  authorizer: none

improv_serial:

binary_sensor:
  - platform: status
    name: Status

  - platform: gpio
    name: Contact
    disabled_by_default: true
    device_class: garage_door
    id: contact
    pin:
      number: GPIO18
      inverted: true
    filters:
      - delayed_on: 20ms

  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: true
    name: Button
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - switch.turn_on: relay
      - timing:
          - ON for at least 4s
        then:
          - button.press: Reset

button:
  - platform: restart
    name: Restart
    entity_category: config

  - platform: factory_reset
    name: Factory Reset
    id: Reset
    entity_category: config

  - platform: safe_mode
    name: Safe Mode
    internal: false
    entity_category: config

switch:
  - platform: gpio
    pin: GPIO7
    name: Relay
    id: relay
    disabled_by_default: true
    on_turn_on:
      - light.turn_on: wifi_led
      - delay: 1s
      - switch.turn_off: relay
      - light.turn_off: wifi_led

light:
  - platform: status_led
    name: Status LED
    id: wifi_led
    disabled_by_default: true
    pin: GPIO4

cover:
  - platform: template
    device_class: garage
    name: None
    lambda: "return id(contact).state ? COVER_OPEN : COVER_CLOSED;"
    open_action:
      then:
        - if:
            condition:
              lambda: "return !id(contact).state;"
            then:
              - switch.turn_on: relay
    stop_action:
      - switch.turn_on: relay
    close_action:
      then:
        - if:
            condition:
              lambda: "return id(contact).state;"
            then:
              - switch.turn_on: relay
