packages:
  device_basis: !include network_ha_config.yaml

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  platform: ESP8266
  board: esp01_1m
  area: ${room}

switch:
  - platform: gpio
    pin: GPIO0
    name: ' '
