packages:
  device_basis: !include network_ha_config.yaml

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: ${room}

esp8266:
  board: esp01_1m

switch:
  - platform: gpio
    pin: GPIO0
    name: " "
