packages:
  device_basis: !include network_ha_config.yaml

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  platform: ESP8266
  board: esp01_1m
  area: ${room}

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 115200

tuya:
  time_id : homeassistant_time
  
light:
  - platform: tuya
    name: ${room} Light
    dimmer_datapoint: 10
    switch_datapoint: 9
    min_value: 100
    max_value: 1000

fan:
  - platform: tuya
    name: ' '
    switch_datapoint: 1
    speed_datapoint: 3
    speed_count: 4
