packages:
  device_basis: !include network_ha_config.yaml

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: ${room}

esp8266:
  board: esp01_1m

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 115200

tuya:
  time_id: homeassistant_time

fan:
  - platform: tuya
    name: " "
    switch_datapoint: 1
    speed_datapoint: 3
    speed_count: 4
