packages:
  device_basis: !include network_ha_config.yaml

substitutions:
  light_min: "100"
  light_max: "1000"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: ${room}

esp8266:
  board: esp01_1m

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 115200

tuya:
  time_id: homeassistant_time

light:
  - platform: tuya
    name: ${room} Light
    dimmer_datapoint: 10
    switch_datapoint: 9
    min_value: ${light_min}
    max_value: ${light_max}
    restore_mode: RESTORE_DEFAULT_OFF

fan:
  - platform: tuya
    name: None
    switch_datapoint: 1
    speed_datapoint: 3
    speed_count: 4
    restore_mode: RESTORE_DEFAULT_OFF
